name: myBoard CI

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - master

jobs:
  build-deploy:
    name: CI/CD Docker Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          node-version: '20'

      - name: Unit Testing
        run: mvn -B test --file pom.xml

      - name: Package and build
        run: mvn clean package --file pom.xml

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u rossypotentials --password-stdin

      - name: Build and push Docker image in Dockerhub
        run: |
          docker build -t rossypotentials/my-board:latest .
          docker push rossypotentials/my-board:latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: rossypotentials/my-board:latest





























#
#
#name: myBoard CI
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'corretto'
#        cache: maven
#    - name: Build with Maven
#      run: mvn -B package --file pom.xml
#
#    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
